### ISSUE TITLE
enable horizontal sharding by subject hashing

### ISSUE THREAD

**Issue by tomatophantastico** [Iranox/mapbench-datadistributor#36]
add subject based sharding by:

calculate a hash, and caclulated the modulo x for an divisor y.
Allow x and y to be defined via the command line to allow a full sharding of a table by issuing:

load -table product -cols name,date -x 0 -y 3
load -table product -cols name,date  -x 1 -y 3
load -table product -cols name,date  -x 2 -y 3

**Comment by Iranox** [comment]
see 3bdb14b
